### ISSUE TITLE
Second order derivatives f_{xu},f_{uu} are all zeros

### ISSUE THREAD

**Issue by chenghuailin** [GeorgeBoutselis/DDP-LieGroups#1]
I've checked and run the codes and it works so far. However, I've also gotten an problem about the linearized dyanmics.

In lineardyn_TSOeul.m where the Jocabian and Hessian is obtained, two of three the second order derivative of dynamics, he f_{xu} and f_{uu} are all set to be zero. To further confirm, I printed out those variables and they are indeed all zeros.

Are you sure this is the right way, or is it a unfinished version of code? For me, it seems a bit wierd that they are all zero, seemingly saying the changes of the input doesn't affect the dyanmics at all. If I'm wrong, can you explain a bit about that?

**Comment by GeorgeBoutselis** [comment]
These are Hessians. It just follows by taking consecutive derivatives of the example posted here. f_{u} is not zero though.
